### PR TITLE
fix(bluefin-wallpapers): fix disappearing wallpapers

### LINKED ISSUE #350: Issues with bluefin-wallpapers
I'm not entirely sure which repository to put this in, but all of the monthly Bluefin wallpapers have vanished from the `bluefin-wallpapers` tap, seemingly overnight! Was it another impact event!?

..Okay, jokes aside, time for for some actual information.

Last month, I installed the `bluefin-wallpapers` and `bluefin-wallpapers-extra` casks onto `bazzite-gnome`. `bluefin-wallpapers-extra` worked out of the box, but `bluefin-wallpapers` only included the contents of `/.local/share/gnome-background-properties`, meaning that I had to install the intended contents of `/.local/share/backgrounds/bluefin` myself.

Tonight, I received the update to the `bluefin-wallpapers-extra` tap, but mysteriously, all of the images from the `bluefin-wallpapers` cask seem to have vanished again. I can only assume that this was brew doing what it thought was some cleanup of the files I created.

The issue here, I think, really is just that the contents of `/local/share/backgrounds/bluefin` aren't being included with the `bluefin-wallpapers` cask.

The casks installed, shown when I run `brew list`:
```
==> Casks
bluefin-wallpapers  bluefin-wallpapers-extra
```

### PR DESCRIPTION
**Pull request by castrojo**
Wallpapers were disappearing for people not on bluefin (since those are on the image) so you have to be on a non-bluefin to notice this: 

Fixes: https://github.com/ublue-os/homebrew-tap/issues/350

Agent notes:

bluefin-wallpapers.rb:
- Fix GNOME artifact glob: s/images\/*/\.select { File.file? }/ — the gnome tarball has .jxl and transition .xml files at the archive root, not under images/. The broken glob was introduced in 1bf7e37 (Nov 2025) when per-type tarballs were adopted; the glob was never updated to match the new layout. Every GNOME install since Nov 29 2025 silently dropped all wallpaper images and transition XMLs from ~/.local/share/backgrounds/bluefin.
- Bump to 2026-04-13 with updated sha256 for all four variants.

bluefin-wallpapers-extra.rb:
- Fix uninstall_postflight: replace FileUtils.rm_r on the shared backgrounds/bluefin directory with surgical broken-symlink removal. The old rm_r nuked the entire shared directory on every upgrade, destroying files installed by bluefin-wallpapers (and any manual user additions). The new code removes only symlinks that point to the now-deleted old staged path; artifact symlinks from bluefin-wallpapers point to a separate Caskroom path and survive. Full directory removal is still available via brew uninstall --zap.

Assisted-by: Claude Sonnet 4.6 via GitHub Copilot

### CODE REVIEW

File: Casks/bluefin-wallpapers-extra.rb [hunk 1]
```diff
@@ -89,8 +89,27 @@
...
+      # Remove only the symlinks this cask created via postflight. During upgrade,
+      # these point to the old staged path (now being removed) and become broken.
+      # Symlinks from bluefin-wallpapers point to a separate Caskroom path that is
+      # not being removed, so they remain valid and are intentionally left alone.
+      [bg_dir, kde_dir].each do |dir|
+        next unless Dir.exist?(dir)
+        Dir.glob("#{dir}/**/*").sort.reverse.each do |f|
+          File.unlink(f) if File.symlink?(f) && !File.exist?(f)
+          Dir.rmdir(f) rescue nil if File.directory?(f) && Dir.empty?(f)
+        end
```
Comment (hanthor) [inline Casks/bluefin-wallpapers-extra.rb:113]:
```suggestion
        next unless Dir.exist?(dir)

        Dir.glob("#{dir}/**/*").reverse_each do |f|
          File.unlink(f) if File.symlink?(f) && !File.exist?(f)
          if File.directory?(f) && Dir.empty?(f)
            begin
              Dir.rmdir(f)
            rescue StandardError
              nil
            end
          end
        end
```
Fixes four RuboCop offenses caught by `brew style`:
- **Layout/EmptyLineAfterGuardClause**: add blank line after `next unless`
- **Lint/RedundantDirGlobSort**: remove redundant `.sort` (glob results are unsorted by definition)
- **Performance/ReverseEach**: use `reverse_each` instead of `.reverse.each`
- **Style/RescueModifier**: replace inline `rescue` with a `begin/rescue/end` block

**Review by hanthor — COMMENTED** [review]
The  check is failing on four RuboCop offenses in this file. Here's a suggestion to fix them all at once:

File: Casks/bluefin-wallpapers-extra.rb (hunk 1 above)
Comment (ahmedadan) [reply Casks/bluefin-wallpapers-extra.rb:113]: I ran `brew style . --fix` and it auto-resolved three of the issues and I fixed the fourth manually
